version: '3.1'
services:
  redis:
    image: redis:4.0.8-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8083:8081
    networks:
      - redis-net
    depends_on:
      - redis

networks:
  redis-net:

volumes:
  redis-data: